### ISSUE TITLE
heads up: grafana 2.0 coming soon

### ISSUE THREAD

**Issue by neoice** [bfraser/puppet-grafana#23]
http://grafana.org/blog/2015/01/12/grafana2-the-future-and-raintank.html
http://grafana.org/blog/2015/02/10/Grafana-2-Alpha-and-preview.html
http://grafana.org/blog/2015/03/30/Grafana-2-Beta1.html
http://docs.grafana.org/installation/migrating_to2/

I think the most painful change is probably going to be the "datasource" configuration. it now lives in a database. a custom provider could be written to use the Grafana HTTP API to create/update/delete datasources.

they also ship .deb/.rpm, so installation could be updated to use those sources.

**Comment by bfraser** [comment]
Agreed. I've been watching for this for the past couple of months. I'm particularly interested in the authentication options, organization and role functionality, and the data backend which means it is no longer necessary to store dashboard data in Elasticsearch.

**Comment by bfraser** [comment]
I've begun work on a version of the module that works with Grafana 2.0 and have committed the changes into the [develop](https://github.com/bfraser/puppet-grafana/tree/develop) branch of the repository.

There is obviously a lot of work to do still, but please test the module and let me know what you think. Thanks!

**Comment by tomtheun** [comment]
@bfraser, works perfectly on Debian 7. Any idea when you are going work on managing the configuration file?

**Comment by forty4487** [comment]
@bfraser, real quick question.  are the configs available in 1.x still available in the dev branch or have you only setup the install method?

**Comment by bfraser** [comment]
@tomtheun yes, ASAP :)

Seriously though, my plan was to get out an initial version of the module that handles basic installation and management of the service, since it is no longer served up by a separate web server, and that full management of the configuration including support for datasources etc would be put in place over time.

@forty4487 No they are not, and the reason for that is Grafana 2.0 is not backwards compatible with 1.x. It now runs as its own web service, has an ini-style configuration file, and has its own backend (sqlite, mysql, etc) where configuration of datasources etc resides.

As @neoice eluded to in his post, ultimately it would make sense to implement a provider that manages this configuration using the [HTTP API](http://docs.grafana.org/reference/http_api/) (yet to be written).

**Comment by tomtheun** [comment]
@bfraser, great to hear, let me know if I can do anything to help.

**Comment by bfraser** [comment]
Thanks @tomtheun I would welcome any pull requests to implement class parameters and management of Grafana 2.0 [configuration](http://docs.grafana.org/installation/configuration/), as well as any implementation of a provider to work with the HTTP API.

**Comment by tomtheun** [comment]
@bfraser, any preference for either doing the config with a template or https://forge.puppetlabs.com/puppetlabs/inifile?

**Comment by bfraser** [comment]
@tomtheun using inifile seems like a clean, supported way of doing it, so I would be for that approach I think

**Comment by bfraser** [comment]
Closing as a version of the module supporting Grafana 2.0.1 has been released.
